basket_craft:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST') }}"
      user: "{{ env_var('PG_USER') }}"
      password: "{{ env_var('PG_PASSWORD') }}"
      port: "{{ env_var('PG_PORT') | int }}"
      dbname: "{{ env_var('PG_DB') }}"
      schema: raw_raw
      threads: 1
