basket_craft_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: isba-dev-02.cxue0o466fzu.us-east-1.rds.amazonaws.com
      user: postgres
      password: isba_4715
      port: 5432
      dbname: postgres
      schema: raw  
      threads: 1
