name: pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DB: ${{ secrets.MYSQL_DB }}
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_PORT: ${{ secrets.PG_PORT }}
      PG_DB: ${{ secrets.PG_DB }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ELT script
        run: python elt/basket_craft_website_sessions_extract_load_raw.py

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Run dbt models
        run: |
          mkdir -p ~/.dbt
          cp profiles/profiles.yml ~/.dbt/profiles.yml
          cd basket_craft_dbt
          dbt deps
          dbt run
        env:
          DBT_USER: ${{ secrets.PG_USER }}
          DBT_PASSWORD: ${{ secrets.PG_PASSWORD }}
          DBT_HOST: ${{ secrets.PG_HOST }}
          DBT_PORT: ${{ secrets.PG_PORT }}
          DBT_DBNAME: ${{ secrets.PG_DB }}
          DBT_SCHEMA: raw
